# Generated by Django 3.2.1 on 2021-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiretubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('tuber_id', models.IntegerField(blank=True)),
                ('tuber_name', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
