# Generated by Django 3.2 on 2021-05-03 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
