# Generated by Django 3.2 on 2021-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_teams_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='yt_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
