# Generated by Django 3.2.1 on 2021-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_teams_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_description', models.CharField(max_length=255)),
                ('first_photo', models.ImageField(upload_to='media/aboutus/%Y/%m')),
                ('second_description', models.CharField(max_length=255)),
                ('second_photo', models.ImageField(upload_to='media/aboutus/%Y/%m')),
            ],
        ),
    ]
