# Generated by Django 3.2.1 on 2021-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20210508_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='first_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='first_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='second_description',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='second_photo',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
