# Generated by Django 3.2 on 2021-05-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Youtubers',
            new_name='Youtuber',
        ),
    ]
